### ISSUE TITLE
Add conda recipe template

### ISSUE THREAD

**Issue by tacaswell** [phobson/pytemplate#1]
I would use something like this:

``` yaml
package:
  name: conda-build
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}


source:
  git_url: ../

build:
  number: 0

  # Note that this will override the default build string with the Python
  # and NumPy versions
  string: {{ environ.get('GIT_BUILD_STR', '') }}_{{ py }}

```

for the top of the template.
